"""Event type definitions for MediaForge event system.

This module defines all event types used throughout the application
for decoupled component communication.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, UTC
from typing import Any, Dict, Optional


@dataclass
class Event:
    """Base event class - all events inherit from this.
    
    Attributes:
        timestamp: When the event was created (auto-generated)
        source: Identifier of the component that emitted the event
    """
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    source: str = "unknown"
    
    @property
    def event_type(self) -> str:
        """Get the event type name."""
        return self.__class__.__name__


# ============================================================================
# Scanning Events
# ============================================================================

@dataclass
class ScanStartedEvent(Event):
    """Fired when a directory scan begins.
    
    Attributes:
        scan_path: Path being scanned
        recursive: Whether scanning subdirectories
        incremental: Whether skipping unchanged files
    """
    scan_path: str = ""
    recursive: bool = True
    incremental: bool = True


@dataclass
class ScanProgressEvent(Event):
    """Fired during scan progress updates.
    
    Attributes:
        processed: Number of files processed so far
        total: Total number of files to process
        current_file: Path of file currently being processed
    """
    processed: int = 0
    total: int = 0
    current_file: str = ""
    
    @property
    def percentage(self) -> float:
        """Calculate completion percentage."""
        if self.total <= 0:
            return 0.0
        return (self.processed / self.total) * 100.0


@dataclass
class ScanCompletedEvent(Event):
    """Fired when a scan completes.
    
    Attributes:
        new_files: Number of new files discovered
        updated_files: Number of existing files updated
        skipped_files: Number of files skipped (unchanged)
        errors: Number of errors encountered
        duration_seconds: Total scan duration
    """
    new_files: int = 0
    updated_files: int = 0
    skipped_files: int = 0
    errors: int = 0
    duration_seconds: float = 0.0


@dataclass
class MediaDiscoveredEvent(Event):
    """Fired when a new media file is discovered.
    
    Attributes:
        file_path: Path to the discovered file
        file_hash: SHA-256 hash of the file
        media_type: Type of media (video, audio, image)
        file_size: File size in bytes
        media_id: Database ID (if saved)
    """
    file_path: str = ""
    file_hash: str = ""
    media_type: str = ""
    file_size: int = 0
    media_id: Optional[str] = None


# ============================================================================
# Metadata Events
# ============================================================================

@dataclass
class MetadataExtractedEvent(Event):
    """Fired when metadata extraction completes for a file.
    
    Attributes:
        media_id: Database ID of the media item
        file_path: Path to the file
        metadata: Dictionary of extracted metadata
        duration_seconds: Extraction duration
    """
    media_id: str = ""
    file_path: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    duration_seconds: float = 0.0


# ============================================================================
# Tag & Collection Events
# ============================================================================

@dataclass
class TagAddedEvent(Event):
    """Fired when a tag is added to a media item.
    
    Attributes:
        media_id: ID of the media item
        tag_id: ID of the tag
        tag_name: Name of the tag
        auto_generated: Whether tag was auto-generated by ML
    """
    media_id: str = ""
    tag_id: str = ""
    tag_name: str = ""
    auto_generated: bool = False


@dataclass
class TagRemovedEvent(Event):
    """Fired when a tag is removed from a media item.
    
    Attributes:
        media_id: ID of the media item
        tag_id: ID of the tag
        tag_name: Name of the tag
    """
    media_id: str = ""
    tag_id: str = ""
    tag_name: str = ""


@dataclass
class CollectionUpdatedEvent(Event):
    """Fired when a collection is modified.
    
    Attributes:
        collection_id: ID of the collection
        collection_name: Name of the collection
        action: Type of update (created, updated, deleted, item_added, item_removed)
        media_ids: IDs of affected media items
    """
    collection_id: str = ""
    collection_name: str = ""
    action: str = ""
    media_ids: list[str] = field(default_factory=list)


# ============================================================================
# File System Events
# ============================================================================

@dataclass
class FileChangedEvent(Event):
    """Fired when a watched file changes.
    
    Attributes:
        file_path: Path to the changed file
        change_type: Type of change (created, modified, deleted, moved)
        old_path: Previous path (for moved files)
    """
    file_path: str = ""
    change_type: str = ""
    old_path: Optional[str] = None


# ============================================================================
# Task Events
# ============================================================================

@dataclass
class TaskProgressEvent(Event):
    """Fired when a background task progress updates.
    
    Attributes:
        task_id: Unique task identifier
        task_type: Type of task (e.g., "extract_metadata")
        progress: Progress from 0.0 to 1.0
        message: Optional progress message
    """
    task_id: str = ""
    task_type: str = ""
    progress: float = 0.0
    message: str = ""


@dataclass
class TaskCompletedEvent(Event):
    """Fired when a background task completes.
    
    Attributes:
        task_id: Unique task identifier
        task_type: Type of task
        success: Whether task succeeded
        result: Task result (if successful)
        error: Error message (if failed)
        duration_seconds: Task duration
    """
    task_id: str = ""
    task_type: str = ""
    success: bool = True
    result: Any = None
    error: Optional[str] = None
    duration_seconds: float = 0.0


# ============================================================================
# Error Events
# ============================================================================

@dataclass
class ErrorEvent(Event):
    """Fired when an error occurs.
    
    Attributes:
        error_type: Type/class of error
        message: Error message
        file_path: Related file path (if applicable)
        recoverable: Whether the error is recoverable
        details: Additional error details
    """
    error_type: str = ""
    message: str = ""
    file_path: Optional[str] = None
    recoverable: bool = True
    details: Dict[str, Any] = field(default_factory=dict)
